#Dockerfile for backend development environment
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

# Copy source code
COPY src ./src

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]